### ISSUE TITLE
Incorrect servos behavior in calibration mode

### ISSUE THREAD

**Issue by MrDobromir** [PetoiCamp/OpenCat-Quadruped-Robot#4]
Robot still reading the body angle and try to rebalance if it's over a safe angle in calibration mode. Reference: [Servos move in calibration mode](https://www.petoi.com/forum/basic-assembly-and-setup/servos-move-in-calibration-mode)

**Comment by borntoleave** [comment]
I have disabled the gyro in calibration mode in the last update. But you will need to turn on the gyro after exiting the calibration mode.
