### ISSUE TITLE
WriteInstinct Missing Dependency 

### ISSUE THREAD

**Issue by Kenttleton** [PetoiCamp/OpenCat-Quadruped-Robot#5]
Under the WriteInstinct.ino is missing the Adafruit_PWMServoDriver.h file referenced in OpenCat.h. I was able to track down the library this is from but it should either be included or at least documentation on where to get the library would be helpful.

**Comment by Cosmosauras** [comment]
Doc is here:

https://bittle.petoi.com/4-configuration

**Comment by borntoleave** [comment]
I added the link to the [documentation center](https://docs.petoi.com) in Readme.
